services:
  # Backend API Service
  - type: web
    name: ibm-knowledge-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  # Frontend Web Service
  - type: web
    name: ibm-knowledge-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ibm-knowledge-backend.onrender.com 